Enh/c+r
lbl-cbg/lmcontrol pull request #18
Opened 2024-10-24 22:54 UTC by NiranjanChaudhari0929

Creating a "Draft Pull Request" so that you can review the code and let me know for any updates.

2024-10-25 19:00 UTC, ajtritt requested changes

2024-10-25 22:00 UTC, NiranjanChaudhari0929 commented on scripts/.ipynb_checkpoints/train_simple-checkpoint.sh
I will delete this

2024-10-25 23:48 UTC, ajtritt requested changes

2024-10-25 23:48 UTC, ajtritt commented on src/lmcontrol/data_utils.py
> +                metadata.setdefault(k, []).extend(np.array(npz[k])[indices])
```suggestion
        for k in md_keys:
            v = metadata.setdefault(k, list())
            v.extend([str(npz[k])] * len(npz['masks']))
```

2024-10-25 23:48 UTC, ajtritt commented on src/lmcontrol/data_utils.py
> +                metadata.setdefault(k, []).extend(np.array(npz[k])[indices])
check to make sure this works.

2024-10-25 23:55 UTC, ajtritt requested changes

2024-10-25 23:55 UTC, ajtritt commented on src/lmcontrol/nn/clf.py
> +        self.backbone = resnet(weights=None, progress=True, label_type=label_type, block=block, layers=layers, planes=planes, num_outputs=num_outputs, return_embeddings=return_embeddings)
```suggestion
        self.backbone = ResNet(label_type=label_type, block=block, layers=layers, planes=planes, num_outputs=num_outputs, return_embeddings=return_embeddings)```

2024-10-25 23:55 UTC, ajtritt commented on src/lmcontrol/nn/clf.py
> +
```suggestion
```

2024-10-25 23:55 UTC, ajtritt commented on src/lmcontrol/nn/clf.py
> +from lmcontrol.nn.resnet import _resnet
```suggestion
from lmcontrol.nn.resnet import ResNet
```

2024-10-25 23:55 UTC, ajtritt commented on src/lmcontrol/nn/dataset.py
> +
```suggestion
```

2024-10-25 23:55 UTC, ajtritt commented on src/lmcontrol/nn/resnet.py
> +    return model
```suggestion
```

2024-10-26 00:02 UTC, ajtritt approved these changes

2024-10-26 00:03 UTC, merged